CREATE DATABASE my_project;
USE my_project;
select * from customer_shopping_behaviour limit 10;
--------------------------------------------------------------------------------------------------------
-- Bussiness Insights Questions 
--------------------------------------------------------------------------------------------------------
-- 1.. Which category generates highest revenue 

SELECT 
    category, ROUND(SUM(Purchase_amount), 2) AS revenue
FROM
    customer_shopping_behaviour
GROUP BY category
ORDER BY revenue DESC;
-- bussiness insights :- Company does know which category give more profit 

-- 2.. are discount actually increase purchase value ?

SELECT 
    Discount_Applied, ROUND(SUM(Purchase_amount), 2) AS revenue
FROM
    customer_shopping_behaviour
GROUP BY Discount_Applied;


-- 3. Whats is total revenue generated by genders ;
SELECT 
    gender, ROUND(SUM(purchase_amount), 1) AS revenue
FROM
    customer_shopping_behaviour
GROUP BY gender;


-- 4 . Which customer  used a discount  but still  spent more than the average  purchase amount ?

SELECT 
    customer_id,
    Discount_Applied,
    ROUND(purchase_amount, 2) AS purchase
FROM
    customer_shopping_behaviour
WHERE
    Discount_Applied = 'Yes'
        AND Purchase_amount > (SELECT 
            AVG(Purchase_amount)
        FROM
            customer_shopping_behaviour)
LIMIT 10;

-- 5. which are the  top and bottom 5 products with highest average review rating 

	
SELECT 
    Item_Purchased, round(AVG(Review_Rating),1) AS avg_rating
FROM
    customer_shopping_behaviour
GROUP BY Item_Purchased
ORDER BY avg_rating desc limit 5;

 -- 6. average purchase : standard vs express shipping 
 
 
 SELECT 
    shipping_type,
    COUNT(Customer_ID) AS orders,
    ROUND(AVG(purchase_amount), 2) AS avg_purchase,
    ROUND(SUM(Purchase_amount)) AS revenue
FROM
    customer_shopping_behaviour
WHERE
    Shipping_Type IN ('Standard' , 'Express')
GROUP BY Shipping_Type;

-- 7. Do subscribed  customers spend more ? compare  average speed and total revenue between subscribed and non - subscribed 


SELECT 
    subscription_status,
    COUNT(Customer_ID) AS users,
    ROUND(SUM(purchase_amount), 2) AS revenue,
    ROUND(AVG(Purchase_amount), 2) AS avg_purchase
FROM
    customer_shopping_behaviour
GROUP BY Subscription_Status;


-- 8.  top 5 products with highests discount usage% 

SELECT 
    Item_purchased,
    ROUND(SUM(purchase_amount), 2) AS revenue,
    COUNT(*) AS total_sales,
    COUNT(CASE WHEN Discount_Applied = 'Yes' THEN 1 END) AS discount_sales,
    ROUND(
        COUNT(CASE WHEN Discount_Applied = 'Yes' THEN 1 END) * 100.0 / COUNT(*),
        2
    ) AS discount_usage_percent
FROM customer_shopping_behaviour
GROUP BY Item_purchased
ORDER BY revenue DESC
LIMIT 5;

-- 9. segment customer into new, returning and loyal based on their total number of previous purchase and show the count of each segment 


SELECT 
    CASE
        WHEN Previous_Purchases = 0 THEN 'new customer'
        WHEN Previous_purchases BETWEEN 1 AND 15 THEN 'Returning customer'
        ELSE 'Loyal customer '
    END AS customer_segment,
    COUNT(*) AS customer_count
FROM
    customer_shopping_behaviour
GROUP BY customer_segment;

-- 10. what are the top 3 most purchased products within each category

SELECT *
FROM (
    SELECT 
        category,
        item_purchased,
        COUNT(*) AS purchase_count,
        RANK() OVER (
            PARTITION BY category 
            ORDER BY COUNT(*) DESC
        ) AS rnk
    FROM customer_shopping_behaviour
    GROUP BY category, item_purchased
) t
WHERE rnk <= 3;


-- 11. are customers who are repeat buyers (more than 5 previous purchases ) also likely to subscribe?

select * from customer_shopping_behaviour limit 10;

SELECT 
    CASE
        WHEN Previous_Purchases > 5 THEN 'Repeat '
        ELSE 'normal buyer'
    END AS customer_type,
    Subscription_Status,
    COUNT(*) AS customer
FROM
    customer_shopping_behaviour
GROUP BY customer_type,Subscription_Status;

-- 12. what is the revenue  contribution of each age group ?

select case when age between 18 and 25 then "18-25" 
when age between 26 and 35 then "26-35"
when age between 36 and 50 then "36-50"

else "51+"
end as age_group ,round(sum(purchase_amount),2) as total_revenue
from customer_shopping_behaviour group by age_group;






